(dp1
S'output'
p2
S"<type 'exceptions.ValueError'> invalid literal for long() with base 10: '[3]'"
p3
sS'layer'
p4
S'/Users/ecain/Projects/SOTA/web2py/applications/SOTA/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x11172f230, file "/Users/ecain/Projects/SOTA/web2py/applications/SOTA/controllers/default.py:index", line 10>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/Users/ecain/Projects/SOTA/web2py/gluon/restricted.py", line 216, in restricted\n    exec(ccode, environment)\n  File "/Users/ecain/Projects/SOTA/web2py/applications/SOTA/controllers/default.py:index", line 185, in <module>\n  File "/Users/ecain/Projects/SOTA/web2py/gluon/globals.py", line 405, in <lambda>\n    self._caller = lambda f: f()\n  File "/Users/ecain/Projects/SOTA/web2py/gluon/tools.py", line 4321, in f\n    return action(*a, **b)\n  File "/Users/ecain/Projects/SOTA/web2py/applications/SOTA/controllers/default.py:index", line 25, in index\n  File "/Users/ecain/Projects/SOTA/web2py/gluon/tools.py", line 4321, in f\n    return action(*a, **b)\n  File "/Users/ecain/Projects/SOTA/web2py/applications/SOTA/controllers/default.py:index", line 173, in database_contents\n  File "/Users/ecain/Projects/SOTA/web2py/gluon/sqlhtml.py", line 2997, in grid\n    selectable(records)\n  File "/Users/ecain/Projects/SOTA/web2py/applications/SOTA/controllers/default.py:index", line 173, in <lambda>\n  File "/Users/ecain/Projects/SOTA/web2py/applications/SOTA/controllers/default.py:index", line 180, in some_func\n  File "/usr/local/lib/python2.7/site-packages/pydal/objects.py", line 2045, in select\n    return adapter.select(self.query, fields, attributes)\n  File "/usr/local/lib/python2.7/site-packages/pydal/adapters/sqlite.py", line 82, in select\n    return super(SQLite, self).select(query, fields, attributes)\n  File "/usr/local/lib/python2.7/site-packages/pydal/adapters/base.py", line 741, in select\n    colnames, sql = self._select_wcols(query, fields, **attributes)\n  File "/usr/local/lib/python2.7/site-packages/pydal/adapters/base.py", line 611, in _select_wcols\n    colnames = list(map(self._colexpand, fields))\n  File "/usr/local/lib/python2.7/site-packages/pydal/adapters/base.py", line 553, in _colexpand\n    return self.expand(field, colnames=True)\n  File "/usr/local/lib/python2.7/site-packages/pydal/adapters/base.py", line 441, in _expand\n    rv = op(first, second, **optional_args)\n  File "/usr/local/lib/python2.7/site-packages/pydal/dialects/base.py", line 312, in eq\n    self.expand(first), self.expand(second, first.type))\n  File "/usr/local/lib/python2.7/site-packages/pydal/dialects/__init__.py", line 96, in expand\n    return self.adapter.expand(*args, **kwargs)\n  File "/usr/local/lib/python2.7/site-packages/pydal/adapters/base.py", line 451, in _expand\n    rv = self.represent(expression, field_type)\n  File "/usr/local/lib/python2.7/site-packages/pydal/adapters/base.py", line 385, in represent\n    return super(SQLAdapter, self).represent(obj, field_type)\n  File "/usr/local/lib/python2.7/site-packages/pydal/adapters/base.py", line 334, in represent\n    return self.representer.represent(obj, field_type)\n  File "/usr/local/lib/python2.7/site-packages/pydal/representers/__init__.py", line 251, in represent\n    rv = self.get_representer_for_type(field_type)(rv, field_type)\n  File "/usr/local/lib/python2.7/site-packages/pydal/representers/__init__.py", line 139, in __call__\n    return self.adapt(self.call(value, field_type))\n  File "/usr/local/lib/python2.7/site-packages/pydal/representers/__init__.py", line 136, in _call\n    return self.inner_call(value)\n  File "/usr/local/lib/python2.7/site-packages/pydal/representers/__init__.py", line 124, in _inner_call\n    return self.obj.f(self.representer, value, **kwargs)\n  File "/usr/local/lib/python2.7/site-packages/pydal/representers/base.py", line 26, in _id\n    return str(long(value))\nValueError: invalid literal for long() with base 10: \'[3]\'\n'
p11
s.