(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'Query' object has no attribute 'type'"
p3
sS'layer'
p4
S'/Users/ecain/Projects/SOTA/web2py/applications/SOTA/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x11172f9b0, file "/Users/ecain/Projects/SOTA/web2py/applications/SOTA/controllers/default.py:index", line 10>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/Users/ecain/Projects/SOTA/web2py/gluon/restricted.py", line 216, in restricted\n    exec(ccode, environment)\n  File "/Users/ecain/Projects/SOTA/web2py/applications/SOTA/controllers/default.py:index", line 185, in <module>\n  File "/Users/ecain/Projects/SOTA/web2py/gluon/globals.py", line 405, in <lambda>\n    self._caller = lambda f: f()\n  File "/Users/ecain/Projects/SOTA/web2py/gluon/tools.py", line 4321, in f\n    return action(*a, **b)\n  File "/Users/ecain/Projects/SOTA/web2py/applications/SOTA/controllers/default.py:index", line 25, in index\n  File "/Users/ecain/Projects/SOTA/web2py/gluon/tools.py", line 4321, in f\n    return action(*a, **b)\n  File "/Users/ecain/Projects/SOTA/web2py/applications/SOTA/controllers/default.py:index", line 173, in database_contents\n  File "/Users/ecain/Projects/SOTA/web2py/gluon/sqlhtml.py", line 2997, in grid\n    selectable(records)\n  File "/Users/ecain/Projects/SOTA/web2py/applications/SOTA/controllers/default.py:index", line 173, in <lambda>\n  File "/Users/ecain/Projects/SOTA/web2py/applications/SOTA/controllers/default.py:index", line 180, in some_func\n  File "/usr/local/lib/python2.7/site-packages/pydal/objects.py", line 2045, in select\n    return adapter.select(self.query, fields, attributes)\n  File "/usr/local/lib/python2.7/site-packages/pydal/adapters/sqlite.py", line 82, in select\n    return super(SQLite, self).select(query, fields, attributes)\n  File "/usr/local/lib/python2.7/site-packages/pydal/adapters/base.py", line 741, in select\n    colnames, sql = self._select_wcols(query, fields, **attributes)\n  File "/usr/local/lib/python2.7/site-packages/pydal/adapters/base.py", line 612, in _select_wcols\n    sql_fields = \', \'.join(map(self._geoexpand, fields))\n  File "/usr/local/lib/python2.7/site-packages/pydal/adapters/base.py", line 556, in _geoexpand\n    if isinstance(field.type, str) and field.type.startswith(\'geo\') and \\\nAttributeError: \'Query\' object has no attribute \'type\'\n'
p11
s.