(dp1
S'output'
p2
S"<type 'exceptions.SyntaxError'> Field applicable_oem does not belong to the table"
p3
sS'layer'
p4
S'/Users/ecain/Projects/SOTA/web2py/applications/SOTA/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x10b6aa030, file "/Users/ecain/Projects/SOTA/web2py/applications/SOTA/controllers/default.py:index", line 10>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/Users/ecain/Projects/SOTA/web2py/gluon/restricted.py", line 216, in restricted\n    exec(ccode, environment)\n  File "/Users/ecain/Projects/SOTA/web2py/applications/SOTA/controllers/default.py:index", line 174, in <module>\n  File "/Users/ecain/Projects/SOTA/web2py/gluon/globals.py", line 405, in <lambda>\n    self._caller = lambda f: f()\n  File "/Users/ecain/Projects/SOTA/web2py/gluon/tools.py", line 4321, in f\n    return action(*a, **b)\n  File "/Users/ecain/Projects/SOTA/web2py/applications/SOTA/controllers/default.py:index", line 28, in index\n  File "/Users/ecain/Projects/SOTA/web2py/gluon/tools.py", line 4321, in f\n    return action(*a, **b)\n  File "/Users/ecain/Projects/SOTA/web2py/applications/SOTA/controllers/default.py:index", line 130, in update_form\n  File "/Users/ecain/Projects/SOTA/web2py/gluon/packages/dal/pydal/objects.py", line 810, in update_or_insert\n    newid = self.insert(**values)\n  File "/Users/ecain/Projects/SOTA/web2py/gluon/packages/dal/pydal/objects.py", line 741, in insert\n    ret = self._db._adapter.insert(self, self._listify(fields))\n  File "/Users/ecain/Projects/SOTA/web2py/gluon/packages/dal/pydal/objects.py", line 651, in _listify\n    \'Field %s does not belong to the table\' % name)\nSyntaxError: Field applicable_oem does not belong to the table\n'
p11
s.