(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'DAL' object has no attribute 'ecu_dbu'"
p3
sS'layer'
p4
S'/Users/ecain/Projects/SOTA/web2py/applications/sota/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x105421a30, file "/Users/ecain/Projects/SOTA/web2py/applications/sota/controllers/default.py:ecu_list", line 10>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/Users/ecain/Projects/SOTA/web2py/gluon/restricted.py", line 216, in restricted\n    exec(ccode, environment)\n  File "/Users/ecain/Projects/SOTA/web2py/applications/sota/controllers/default.py:ecu_list", line 246, in <module>\n  File "/Users/ecain/Projects/SOTA/web2py/gluon/globals.py", line 405, in <lambda>\n    self._caller = lambda f: f()\n  File "/Users/ecain/Projects/SOTA/web2py/applications/sota/controllers/default.py:ecu_list", line 225, in ecu_list\n  File "/usr/local/lib/python2.7/site-packages/pydal/base.py", line 670, in __getattr__\n    return BasicStorage.__getattribute__(self, key)\nAttributeError: \'DAL\' object has no attribute \'ecu_dbu\'\n'
p11
s.